# Generated by Django 5.0.1 on 2024-03-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attainment_status', '0002_data_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
