# Generated by Django 5.0.1 on 2024-03-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
