# Generated by Django 4.2.7 on 2024-04-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file_desc',
        ),
        migrations.DeleteModel(
            name='File_Description',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
