# Generated by Django 4.2.7 on 2024-03-13 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0011_course_outcome_programme_specific_outcomes'),
        ('charts', '0002_student_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.course')),
            ],
        ),
    ]
