# Generated by Django 5.0.1 on 2024-03-29 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_file_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sem_marks',
            new_name='semester_marks',
        ),
        migrations.RemoveField(
            model_name='file_description',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='file_name',
        ),
        migrations.AddField(
            model_name='student',
            name='file_desc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='charts.file_description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file_description',
            name='year',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
