# Generated by Django 5.0.1 on 2024-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_rename_sem_marks_student_semester_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_description',
            name='year',
            field=models.IntegerField(),
        ),
    ]
