# Generated by Django 5.0.1 on 2024-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_alter_file_description_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_description',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
