# Generated by Django 5.0.1 on 2024-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_alter_file_description_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_description',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
