# Generated by Django 5.0.1 on 2024-04-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techapp', '0020_rename_courseprogrammeoutcome_course_programme_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_file', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cia_marks', models.IntegerField()),
                ('semester_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('file_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.file_description')),
            ],
        ),
    ]
