# Generated by Django 5.0.1 on 2024-04-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0021_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_description',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='file_desc',
        ),
    ]
