# Generated by Django 4.2.7 on 2024-04-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0020_rename_courseprogrammeoutcome_course_programme_outcome'),
        ('charts', '0023_file_description_course_student_file_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_description',
            name='year_of_file',
        ),
        migrations.AddField(
            model_name='file_description',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techapp.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file_description',
            name='passout_year',
            field=models.ForeignKey(default=2023, on_delete=django.db.models.deletion.CASCADE, related_name='passout_year', to='techapp.year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file_description',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techapp.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file_description',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techapp.year'),
            preserve_default=False,
        ),
    ]
