# Generated by Django 4.2.7 on 2024-04-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0026_passoutyear_alter_file_description_passout_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_description',
            name='passout_year',
            field=models.CharField(max_length=4),
        ),
    ]
