# Generated by Django 4.2.7 on 2024-04-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0027_alter_file_description_passout_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassoutYear',
        ),
    ]
