# Generated by Django 4.2.7 on 2024-04-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0028_delete_passoutyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassoutYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='file_description',
            name='passout_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.passoutyear'),
        ),
    ]
