# Generated by Django 4.2.7 on 2024-04-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0020_rename_courseprogrammeoutcome_course_programme_outcome'),
        ('charts', '0030_remove_file_description_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttainmentPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_percentage', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.course')),
                ('passout_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.passoutyear')),
            ],
        ),
    ]
