# Generated by Django 5.0.1 on 2024-02-14 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.department')),
                ('programme_specific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.programme_specific')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.semester')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.year')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.subject')),
            ],
        ),
    ]
