# Generated by Django 5.0.1 on 2024-02-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0002_subject_course_outcome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Course',
        ),
    ]
