# Generated by Django 5.0.2 on 2024-02-14 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_rename_subject_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme_specific',
            old_name='department',
            new_name='dept',
        ),
        migrations.RemoveField(
            model_name='programme_specific',
            name='name',
        ),
        migrations.RemoveField(
            model_name='programme_specific_outcome',
            name='programme_specific',
        ),
        migrations.AddField(
            model_name='programme_specific_outcome',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techapp.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
