# Generated by Django 5.0.2 on 2024-02-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0004_rename_department_programme_specific_dept_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme_specific',
            old_name='dept',
            new_name='dep',
        ),
    ]
