# Generated by Django 5.0.2 on 2024-02-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0006_rename_dep_programme_specific_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techapp.year'),
            preserve_default=False,
        ),
    ]
