# Generated by Django 5.0.2 on 2024-02-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0007_semester_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='name',
        ),
    ]
