# Generated by Django 4.2.7 on 2024-03-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0009_rename_dept_programme_specific_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techapp.programme'),
        ),
    ]
