# Generated by Django 4.2.7 on 2024-03-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0010_course_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_outcome',
            name='programme_specific_outcomes',
            field=models.ManyToManyField(to='techapp.programme_specific_outcome'),
        ),
    ]
