# Generated by Django 4.2.7 on 2024-03-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0014_course_outcome_programme_outcomes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme_specific_outcome',
            name='programme_specific',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programme_specific_outcomes', to='techapp.programme_specific'),
            preserve_default=False,
        ),
    ]
