# Generated by Django 4.2.7 on 2024-03-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0015_programme_specific_outcome_programme_specific'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme_specific_outcome',
            name='programme_specific',
        ),
        migrations.AddField(
            model_name='programme_specific',
            name='programme_specific_outcomes',
            field=models.ManyToManyField(related_name='programme_specifics', to='techapp.programme_specific_outcome'),
        ),
    ]
