# Generated by Django 4.2.7 on 2024-03-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0016_remove_programme_specific_outcome_programme_specific_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme_specific',
            name='programme_specific_outcomes',
        ),
    ]
