# Generated by Django 4.2.7 on 2024-03-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0019_courseprogrammeoutcome_course_programme_outcomes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseProgrammeOutcome',
            new_name='Course_Programme_Outcome',
        ),
    ]
